-- ==========================================
-- 1. 啟用密碼加密擴充功能
-- ==========================================
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ==========================================
-- 2. 建立資料表結構 (Schema)
-- ==========================================

-- 管理員資料表
CREATE TABLE IF NOT EXISTS admins (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  username TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL
);

-- 獎池資料表
CREATE TABLE IF NOT EXISTS prize_pool (
  id BIGINT PRIMARY KEY DEFAULT 1,
  first_prize_total INTEGER NOT NULL DEFAULT 0,
  second_prize_total INTEGER NOT NULL DEFAULT 0,
  third_prize_total INTEGER NOT NULL DEFAULT 0,
  first_prize_remaining INTEGER NOT NULL DEFAULT 0,
  second_prize_remaining INTEGER NOT NULL DEFAULT 0,
  third_prize_remaining INTEGER NOT NULL DEFAULT 0,
  team_mapping JSONB,
  is_configured INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 抽獎連線紀錄表
CREATE TABLE IF NOT EXISTS spin_sessions (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  session_id TEXT NOT NULL UNIQUE,
  spin_count INTEGER NOT NULL DEFAULT 0,
  has_won INTEGER NOT NULL DEFAULT 0,
  prize_tier TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- ==========================================
-- 3. 安全性配置 (Security Configuration)
-- POC 階段暫時關閉 RLS 限制，允許後端 API 透過 Anon Key 快速讀寫
-- ==========================================
ALTER TABLE admins DISABLE ROW LEVEL SECURITY;
ALTER TABLE prize_pool DISABLE ROW LEVEL SECURITY;
ALTER TABLE spin_sessions DISABLE ROW LEVEL SECURITY;

-- ==========================================
-- 4. 寫入預設初始資料 (Seeding)
-- ==========================================

-- 寫入預設管理員 (帳號: admin, 密碼: admin)
-- 使用 crypt 函數產生 bcrypt hash，對齊原本 bcrypt.hashSync 的驗證邏輯
INSERT INTO admins (username, password_hash) 
VALUES ('admin', crypt('admin', gen_salt('bf', 10)))
ON CONFLICT (username) DO NOTHING;

-- 寫入預設獎池狀態
INSERT INTO prize_pool (id, is_configured, team_mapping) 
VALUES (1, 0, NULL)
ON CONFLICT (id) DO NOTHING;